# Generated by Django 4.2.17 on 2025-01-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
    ]
